# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Image Description',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='item',
            name='Image File',
            field=models.ImageField(default='', upload_to='user_data/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>'),
        ),
    ]
