# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20171024_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Image Description',
            new_name='imgDesc',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Image File',
        ),
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=main_app.models.UserDirectoryPath),
        ),
    ]
