# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20171105_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sale_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sale_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
