# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20171024_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Image Description',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Image File',
            field=models.ImageField(blank=True, null=True, upload_to='user_data/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>'),
        ),
    ]
