# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20171026_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='dateCreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='dateUpdated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='itemimage',
            old_name='desc',
            new_name='alt',
        ),
        migrations.RenameField(
            model_name='itemimage',
            old_name='img',
            new_name='file',
        ),
    ]
