# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20171027_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='discount_start',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sale_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sale_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='units_available',
            field=models.IntegerField(default=0),
        ),
    ]
