# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20171105_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='units_sold',
            field=models.IntegerField(default=0),
        ),
    ]
