# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_item_units_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='units_purchased',
            field=models.IntegerField(default=0),
        ),
    ]
