# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20171130_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='itemIDs',
            new_name='item_ids',
        ),
    ]
