# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20171212_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsettings',
            name='cart',
            field=models.TextField(blank=True, null=True),
        ),
    ]
