# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_itemunitsolddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemunitsolddate',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
